In [1]:
print('hello')

hello


In [4]:
import numpy as np

print(np.__version__)

2.5.2


In [ ]:
# ModuleNotFoundError : No module named 'torch'
# uv add torch torchvision 으로 설치

import torch

# 버전확인
print(torch.__version__)

# cuda 지원확인
print(torch.cuda.is_available())

2.13.0+cpu
False


PyTorch에서 GPU 가속 사용 가능 여부를 확인하고 장치(Device)를 지정

In [7]:
import torch
import torch.nn as nn

# 1. 실행 환경에 맞는 장치(Device) 동적 할당 (표준 패턴)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("현재 사용 장치:", device)

# 2. 텐서 생성 시 처음부터 지정된 장치로 할당 (메모리 이동 오버헤드 방지)
x = torch.ones((2, 3), device=device)

# 3. 기존 텐서를 지정 장치로 이동
# Note: 텐서의 .to()는 원본을 변경하지 않고 '새로운 텐서'를 반환합니다.
y = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = y.to(device)

# 4. 신경망 모델을 지정 장치로 이동
# Note: 모델의 .to()는 모델 내부 파라미터를 'In-place(제자리)'로 이동시킵니다.
model = nn.Linear(2, 2).to(device)

# 5. 모델 연산 실행
output = model(y)
print("출력 결과 장치:", output.device)

현재 사용 장치: cpu
출력 결과 장치: cpu


## 1.1 데이터로부터 직접 생성(From Data)

In [19]:
a = torch.tensor([[1,2], [3,4]])
print(a)

# python 리스트로부터 생성
list_data = [[1,2,3],[4,5,6]]
print(f'list_data:{list_data}')
type(list_data) # <class 'list'>


tensor_from_list = torch.tensor(list_data, dtype=torch.float32) # dtype 데이터 타입을 명시하지 않으면 입력 데이터에 맞춰 적절한 타입(int64, float32 등)으로 자동 추론합니다.
print(f'List -> Tensor: {tensor_from_list}')
# print(type(tensor_from_list)) #<class 'torch.Tensor'>
print(tensor_from_list.dtype)
print(tensor_from_list.device)

tensor([[1, 2],
        [3, 4]])
list_data:[[1, 2, 3], [4, 5, 6]]
List -> Tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
cpu


In [30]:
# numpy 배열로부터 생성
np_array = np.array([10,20,30])
# from_numpy()으로 tensor()을 생성하면 메모리를 공유한다.
tensor_from_np = torch.from_numpy(np_array) #from_numpy를 이용해서 생성 시 메모리를 공유함 (값 변경 시 같이 변경됨) / torch.tensor는 공유 X
print(f'tensor_from_np:{tensor_from_np}')

tensor_from_np[0] = 999
print(f'np_array: {np_array}')
print(f'tensor_from_np: {tensor_from_np}')

np_array[0] = 500
print(f'np_array: {np_array}')
print(f'tensor_from_np: {tensor_from_np}')

tensor_from_np:tensor([10, 20, 30])
np_array: [999  20  30]
tensor_from_np: tensor([999,  20,  30])
np_array: [500  20  30]
tensor_from_np: tensor([500,  20,  30])


## 1.2 특정 형태(Shape)와 값으로 초기화 (Structured Initalization)

In [ ]:
shape = (2, 3)
print(f'zeros: {torch.zeros(shape)}')
print(f'ones: {torch.ones(shape)}')
print(f'empty: {torch.empty(shape)}')
print(f'full: {torch.full(shape, 3)}')

# 범위 기반 생성
print(f'arange: {torch.arange(10)}') #end
print(f'arange: {torch.arange(0, 10)}') #start, end
print(f'arange: {torch.arange(0,10,2)}') #start, end, steps
# np.arange(0,5)
torch.arange(0,5)


print(f'linspace: {torch.linspace(1, 10, 5)}') #start, end, step(1부터 10까지 5등분)
np.linspace(1, 10, 5, endpoint = False) # linspace는 지정한 범위 내에 일정한 간격으로 잘라서 출력시키고 기본값이 True이기때문에 end값도 포함됨 / endpoint를 False로 둘 경우에는 미포함

zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])
empty: tensor([[2.0157e+00, 7.3288e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
full: tensor([[3, 3, 3],
        [3, 3, 3]])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


array([1. , 2.8, 4.6, 6.4, 8.2])

## 1.3 무작위 난수로 초기화 (Random Initialization)

In [68]:
# 난수 생성 시 재현성을 위한 시드(seed) 고정
torch.manual_seed(42)

print(f'rand: {torch.rand(2, 2)}') # *size 
print(f'rand: {torch.rand((2, 2))}')

print(f'randn: {torch.randn(2, 2)}')
print(f'randint: {torch.randint(10, (2, 2))}') # high, size=()
print(f'randint: {torch.randint(1, 10, (2, 2))}') # low, high, size=()
print(f'randint: {torch.randint(1, 10, (2, 2))}')

# print(f'randperm: {torch.randperm(low=1, high=10, size =(2,2))}') # 0부터 n-1까지만의 정수를 무작위로 섞인 1차 텐서 생성

rand: tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
rand: tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])
randn: tensor([[-1.1229, -0.1863],
        [ 2.2082, -0.6380]])
randint: tensor([[5, 5],
        [7, 6]])
randint: tensor([[5, 9],
        [2, 6]])
randint: tensor([[9, 5],
        [3, 1]])


## 1.4 기존 텐서의 속성을 복사하여 초기화(_like 계열)

In [ ]:
# x = torch.tensor([[1,2,3], [4,5,6]])
x = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
print(f'x: {x}')

#shape와 dtype을 그대로 복사해 온다.
x_zeros = torch.zeros_like(x)
print(f'zeros_like: {x_zeros}, dtype:{x_zeros.dtype}')

x_ones = torch.ones_like(x)
print(f'ones_like: {x_ones}, dtype:{x_ones.dtype}')

x_rand = torch.rand_like(x)
print(f'rand_like: {x_rand}, dtype:{x_rand.dtype}')

x_randint = torch.randint_like(x, 10) # randint_like()는 x의 타입이 float32이므로 그 타입을 그대로 따라서 사용이 된다 .(주의)
print(f'randint_like: {x_randint}, dtype:{x_randint.dtype}')

x: tensor([[1., 2., 3.],
        [4., 5., 6.]])
zeros_like: tensor([[0., 0., 0.],
        [0., 0., 0.]]), dtype:torch.float32
ones_like: tensor([[1., 1., 1.],
        [1., 1., 1.]]), dtype:torch.float32
rand_like: tensor([[0.9497, 0.6666, 0.9811],
        [0.0874, 0.0041, 0.1088]]), dtype:torch.float32
randint_like: tensor([[3., 7., 8.],
        [1., 4., 1.]]), dtype:torch.float32


## 1.5. 텐서의 주요 속성 (Attributes)
https://docs.pytorch.org/docs/2.13/tensor_attributes.html#torch-dtype

In [92]:
# 속성을 명시하며 텐서 생성
tensor_attr = torch.ones((2,3), dtype=torch.float16, device="cpu")
print("Shape(차원):", tensor_attr.shape)
print("Datatype(타입):", tensor_attr.dtype)
print("Device(장치):", tensor_attr.device)

#타입 변경 및 디바이스 이동
tensor_float32 = tensor_attr.to(dtype=torch.float32)
print("변경된 Datatype:", tensor_float32.dtype)

#GPU가 사용 가능한 경우 CUDA 장치로 이동
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("이동된 Device:", device)

Shape(차원): torch.Size([2, 3])
Datatype(타입): torch.float16
Device(장치): cpu
변경된 Datatype: torch.float32
이동된 Device: cpu


# 2.텐서 사이즈(Tensor Size)

## 2.1크기 및 차원 확인(Size Inspection)

In [ ]:
x = torch.arange(24).reshape(2,3,4) #(2,3,4) 크기의 3차원 텐서
# print(f'x: {X}')

print(f'size: {x.shape}') #torch.Size([2, 3, 4])
print(f'ndim: {x.ndim}') # 3
print(f'size: {x.size(0)}') # size(dim) => size(0) => 2 출력  
print(f'numel: {x.numel()}') # 24 : 텐서 내부의 전체요소개수

size: torch.Size([2, 3, 4])
ndim: 3
size: 2
numel: 24


In [96]:
np.shape(x)
np.ndim(x)

2

In [ ]:
x = torch.arange(24).reshape(2,3,4)

# view()
x_view = x.view(2, 12)

2.2 크기 변경 및 형상 조작 (Shape Manipulation)

In [155]:
x = torch.arange(24). reshape(2,3,4) #3차원 텐서

#view와 reshape
x_view = x.view(2,12) #2차원 행렬
print(f'x_view: {x_view}')

x_auto = x.reshape(-1,6)
print(f'x_auto : {x_auto}')

# unsqueeze & squeeze
x_2d = torch.randn(3,4)
print(f'x_2d : {x_2d}')

# unsqueeze(axis): 축을 추가할 때 사용한다. (차원확대)
x_unsqueeze = x_2d.unsqueeze(2)            # 0으로 설정하면 batch 차원 추가함
print(f'x_unsqueezed: {x_unsqueezed.shape}') # torch.Size([1, 3, 4])

# squeeze()는 크기가 1인 차원을 찾아 없애준다.(차원축소)
x_squeeze = x_unsqueeze.squeeze()      
print(f'x_squeeze : {x_squeeze.shape}') # torch.Size([3, 4])

# 4. permute (차원 재배치)
img_tensor = torch.randn(32, 3, 224, 224) # (Batch, Channel, Height, Width)
img_permuted = img_tensor.permute(0, 2, 3, 1) # (Batch, Height, Width, Channel)

print(f'img_permuted: {img_permuted.shape}')  # torch.Size([32, 224, 224, 3])

# 5. expand VS repeat
a = torch.tensor([[1], 
                [2]])       # Shape: (2, 1)


print(f'expand: {a.expand(2,4)}')
print(f'repeat: {a.repeat(1,4)}')

x_view: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
x_auto : tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
x_2d : tensor([[-1.5154, -1.2650, -1.0761, -0.4440],
        [ 1.0450,  1.5403, -0.7781, -1.8284],
        [-0.8380,  0.5665,  0.8395, -0.9763]])
x_unsqueezed: torch.Size([1, 3, 4])
x_squeeze : torch.Size([3, 4])
img_permuted: torch.Size([32, 224, 224, 3])
expand: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])
repeat: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])


## 3. 인덱싱, 슬라이싱 및 결합 (Indexing, Slicing & Joining)

In [159]:
x = torch.tensor([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12]])

print(f'x: {x[1,2]}')           #7
print(f'x: {x[1,2].item()}')    #7

# 2. 특정 행/열 전체 추출
print("2-1. 첫 번째 행 전체(0, :):", x[0, :])
print("2-2. 마지막 열 전체 (:, -1):", x[:, -1])

# 3. 범위 슬라이싱 (0~1행, 1~2열 추출)
# [start:end]에서 end는 포함되지 않음
print("3. 부분 텐서 추출:\n", x[0:2, 1:3])

# 4. 간격 지정 슬라이싱 (step=2)
print("4. 2칸 간격 추출:", x[:, ::2])

x: 7
x: 7
2-1. 첫 번째 행 전체(0, :): tensor([1, 2, 3, 4])
2-2. 마지막 열 전체 (:, -1): tensor([ 4,  8, 12])
3. 부분 텐서 추출:
 tensor([[2, 3],
        [6, 7]])
4. 2칸 간격 추출: tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])


## 3.2 고급 인덱싱 (Advanced Indexing)

In [160]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

# 1. 불리언 마스킹 (50보다 큰 요소만 추출)
mask = x > 50
print("마스크 (Boolean Tensor):\n", mask)
print("50보다 큰 값만 추출:", x[mask])  # 1차원 텐서로 반환됨

# 2. 인덱스 리스트를 활용한 추출 (팬시 인덱싱)
# 0행과 2행 추출
rows = torch.tensor([0, 2])
print("\n0행과 2행 추출:\n", x[rows])

# 3. torch.index_select 사용 (dim=1: 열 기준 추출)
cols = torch.tensor([0, 2]) # 0열과 2열 선택
selected_cols = torch.index_select(x, dim=1, index=cols)
print("0열과 2열 추출 (index_select):\n", selected_cols)

마스크 (Boolean Tensor):
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
50보다 큰 값만 추출: tensor([60, 70, 80, 90])

0행과 2행 추출:
 tensor([[10, 20, 30],
        [70, 80, 90]])
0열과 2열 추출 (index_select):
 tensor([[10, 30],
        [40, 60],
        [70, 90]])


In [161]:
t1 = torch.tensor([[1, 2],
                   [3, 4]])

t2 = torch.tensor([[5, 6],
                   [7, 8]])

# 1. torch.cat (기존 차원 이어붙이기)
# dim=0: 세로 방향(행)으로 붙임
cat_dim0 = torch.cat([t1, t2], dim=0)
print("torch.cat (dim=0) Shape:", cat_dim0.shape)
print(cat_dim0)

# dim=1: 가로 방향(열)으로 붙임
cat_dim1 = torch.cat([t1, t2], dim=1)
print("\ntorch.cat (dim=1) Shape:", cat_dim1.shape)
print(cat_dim1)

# 2. torch.stack (새로운 차원 생성하며 쌓기)
# dim=0: 맨 앞에 새로운 차원 추가 (2, 2, 2)
stacked = torch.stack([t1, t2], dim=0)
print("\ntorch.stack (dim=0) Shape:", stacked.shape)
print(stacked)

torch.cat (dim=0) Shape: torch.Size([4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

torch.cat (dim=1) Shape: torch.Size([2, 4])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

torch.stack (dim=0) Shape: torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
x = torch.randn(2, 3)
torch.stack((x, x), dim=0)

In [162]:
x = torch.randn(2, 3)
torch.stack((x, x), dim=1)

tensor([[[ 0.5345,  1.7330,  0.0082],
         [ 0.5345,  1.7330,  0.0082]],

        [[-2.3600,  1.3305, -0.5374],
         [-2.3600,  1.3305, -0.5374]]])

3.4 텐서 분할 (Splitting Tensors)

In [175]:
x = torch.arange(12).reshape(4, 3) # 4행 3열 텐서
print("분할할 원본 텐서 (4x3):\n", x)

# 1. torch.split: 행 방향(dim=0)으로 2행씩 분할
split_result = torch.split(x, split_size_or_sections=3, dim=0)
print("\nsplit (크기 2씩 분할 결과):")
for t in split_result:
    print(t)

# 2. torch.chunk: 행 방향(dim=0)으로 총 2개의 덩어리로 분할
chunk_result = torch.chunk(x, chunks=3, dim=0)
print("\nchunk (2개로 등분 결과):")
for t in chunk_result:
    print(t)

분할할 원본 텐서 (4x3):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

split (크기 2씩 분할 결과):
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[ 9, 10, 11]])

chunk (2개로 등분 결과):
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])


.4 자동 형변환 및 승격 (Type Promotion)

In [176]:
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor = torch.tensor([0.5, 1.5, 2.5], dtype=torch.float32)

# int32 + float32 -> float32로 자동 승격
result = int_tensor + float_tensor
print("연산 결과:", result)
print("자동 승격된 dtype:", result.dtype) # torch.float32


연산 결과: tensor([1.5000, 3.5000, 5.5000])
자동 승격된 dtype: torch.float32


In [178]:
x = torch.tensor([[1.0, 5.0, 3.0],
                  [4.0, 2.0, 6.0]]) # Shape: (2, 3)

# 1. 전체 요소 집계
print("전체 합:", x.sum().item())
print("전체 평균:", x.mean().item())

# 2. 차원(dim) 기준 집계
# dim=0: 행 방향(세로)으로 뭉쳐서 연산 -> 결과 Shape: (3,)
print("\n열 기준(dim=0) 평균:", x.mean(dim=0))

# dim=1: 열 방향(가로)으로 뭉쳐서 연산 -> 결과 Shape: (2,)
print("행 기준(dim=1) 최댓값:", x.max(dim=1).values)

# 3. keepdim=True 옵션
sum_keepdim = x.sum(dim=1, keepdim=True)
print("\nkeepdim=True 적용 합 Shape:", sum_keepdim.shape) # (2, 1)

# 4. Argmax (최댓값의 인덱스 위치)
print("\n행 기준 가장 큰 값의 인덱스 (dim=1):", x.argmax(dim=1)) # [1, 2]

전체 합: 21.0
전체 평균: 3.5

열 기준(dim=0) 평균: tensor([2.5000, 3.5000, 4.5000])
행 기준(dim=1) 최댓값: tensor([5., 6.])

keepdim=True 적용 합 Shape: torch.Size([2, 1])

행 기준 가장 큰 값의 인덱스 (dim=1): tensor([1, 2])


In [181]:
x = torch.tensor([1.0, 2.0, 3.0])
print("초기 메모리 주소:", id(x))

# Out-of-place 연산 (새로운 텐서 생성 -> 주소 변경됨)
x_new = x + 5.0
print("Out-of-place 후 x 주소:", id(x))
print(f'x_new: {x_new}')

# In-place 연산 (기존 텐서 메모리에 즉시 반영 -> 주소 동일)
x.add_(5.0)
print("In-place 연산 후 x 값:", x)
print("In-place 후 x 주소:", id(x)) # 초기 주소와 동일함

# 모든 요소를 0으로 초기화
x.zero_()
print("zero_() 적용 후:", x)

초기 메모리 주소: 2769823879712
Out-of-place 후 x 주소: 2769823879712
x_new: tensor([6., 7., 8.])
In-place 연산 후 x 값: tensor([6., 7., 8.])
In-place 후 x 주소: 2769823879712
zero_() 적용 후: tensor([0., 0., 0.])
